# Generated by Django 6.0.6 on 2026-09-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('date_of_registration', models.DateField()),
                ('date_of_arrival', models.DateField()),
                ('date_of_joining_settlement', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=10)),
                ('nationality', models.CharField(choices=[('Ugandan', 'Ugandan'), ('Kenyan', 'Kenyan'), ('Tanzanian', 'Tanzanian'), ('Burundian', 'Burundian'), ('Rwandese', 'Rwandese'), ('Somalian', 'Somalian'), ('South Sudanese', 'South Sudanese')], max_length=50)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=50)),
                ('settlement_camp', models.CharField(choices=[('Gulu settlement camp', 'Gulu settlement camp'), ('Arua settlement camp', 'Arua settlement camp'), ('Mbara settlement camp', 'Mbara settlement camp'), ('Kasese settlement camp', 'Kasese settlement camp'), ('Busia settlement camp', 'Busia settlement camp'), ('Mbale settlement camp', 'Mbale settlement camp'), ('Kigezi settlement camp', 'Kigezi settlement camp')], max_length=100)),
            ],
        ),
    ]
