# Generated by Django 6.0.6 on 2026-09-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RefugeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='date_of_arrival',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='date_of_registration',
        ),
    ]
